# -*- coding: utf-8 -*-
"""Emotion detector

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VvhlhT3GcZlvles7HflcmLzppWXl0cNj
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import dataloader, random_split

from torchvision import datasets, transforms
from PIL import Image

import cv2
import time

DATA_DIR = "./data"
IMG_SIZE = 64
BATCH_SIZE = 32
EPOCHS = 30
LEARNING_RATE = 0.001
VAL_SPLIT = 0.2
MODEL_PATH = "./model.pth"

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

class CNN(nn.Module):
    def __init__(self, num_classes):
     super().__init__()
     self.features = nn.Sequential(
        nn.Conv2d(3, 16, kernel_size=3, padding=1),
        nn.ReLU(), nn.MaxPool2d(2),
        nn.Conv2d(16, 32, kernel_size=3, padding=1),
        nn.ReLU(), nn.MaxPool2d(2),
        nn.Conv2d(32, 64, kernel_size=3, padding=1),
        nn.ReLU(), nn.MaxPool2d(2)
    )

     self.classifier = nn.Sequential(
        nn.Flatten(),
        nn.Linear(4096,128),
        nn.ReLU(),
        nn.Dropout(0.4),
        nn.Linear(128,num_classes)
    )

    def forward(self, x):
        x = self.features(x)
        x = self.classifier(x)
        return x

train_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize([0.485,0.456,0.406], [0.229,0.224,0.225])
])
val_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize([0.485,0.456,0.406], [0.229,0.224,0.225])
])



import zipfile
import os
zip_path = 'Testing.zip'
extraction_path = './'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extraction_path)

full_dataset = datasets.ImageFolder(DATA_DIR, transform= train_transform)
len(full_dataset)

class_names = full_dataset.classes
num_class = len(class_names)
class_names

val_count = int(len(full_dataset)*VAL_SPLIT)
train_count = len(full_dataset) - val_count

train, val = random_split(full_dataset, [train_count, val_count])

train_count, val_count

val.dataset.transform = val_transform

train_loader = dataloader.DataLoader(train, batch_size=BATCH_SIZE, shuffle=True, num_workers=12, pin_memory=True)
val_loader = dataloader.DataLoader(val, batch_size=BATCH_SIZE, shuffle=True, num_workers=12, pin_memory=True)

model = CNN(num_classes=num_class).to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)

def train():
  best_acc = 0.0

  for epoch in range(1, EPOCHS + 1):
    model.train()
    avg_loss = 0.0
    avg_correct = 0
    total = 0
    t0 = time.time()
    for images,labels in train_loader:
      images, labels = images.to(device, non_blocking=True), labels.to(device, non_blocking=True)

      optimizer.zero_grad()
      outputs = model(images)
      loss = criterion(outputs, labels)
      loss.backward()
      optimizer.step()

      avg_loss += loss.item()*images.size(0)
      preds = outputs.argmax(dim=1)
      avg_correct += (preds == labels).sum().item()
      total += images.size(0)

    model.eval()
    val_loss = 0.0
    val_correct = 0
    val_total = 0

    with torch.no_grad():
      for images,labels in val_loader:
        images, labels = images.to(device, non_blocking=True), labels.to(device, non_blocking=True)
        outputs = model(images)
        loss = criterion(outputs, labels)

        val_loss += loss.item()*images.size(0)
        preds = outputs.argmax(dim=1)
        val_correct += (preds == labels).sum().item()
        val_total += images.size(0)

    avg_loss /= total
    avg_acc = avg_correct/total
    val_loss /= val_total
    val_acc = val_correct/val_total
    t1 = time.time()
    elapsed = t1-t0
    print(f"EPOCH {epoch}/{EPOCHS}  train_loss={avg_loss:.3f} train_acc={avg_acc:.3f}  val_loss={val_loss:.3f} val_acc={val_acc:.3f}  time={elapsed:.1f}s")

    if val_acc>best_acc:
      best_acc = val_acc
      torch.save({
          "model_state" : model.state_dict(),
          "class_names" : class_names,
          "img_size" : IMG_SIZE
      }, MODEL_PATH)

      print(f"Saving the model with the best validation accuracy : {best_acc:.3f} to {MODEL_PATH}")

  print("Training completed")

def inference():
  checkpoint = torch.load(MODEL_PATH,map_location=device)
  model.load_state_dict(checkpoint["model_state"])
  model.to(device)
  model.eval()
  class_names = checkpoint["class_names"]

  print("Webcam is starting... press q to quit")
  webcam = cv2.VideoCapture(0)
  if not webcam.isOpened():
    print("Webcam error")
    return

  while True:
    ret, frame = webcam.read()

    if not ret:
      break

    rbg = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    resize_img = Image.fromarray(rbg).resize((IMG_SIZE, IMG_SIZE))
    tensor = transforms.functional.to_tensor(resize_img)
    tensor = transforms.functional.normalize(tensor,[0.485,0.456,0.406],[0.229,0.224,0.225])
    tensor = tensor.unsqueeze(0).to(device)

    with torch.no_grad():
      out = model(tensor)
      probs = torch.nn.functional.softmax(out, dim=1)
      top_prob, prob_idx = torch.max(probs, dim=1)
      label = class_names[prob_idx.item()]
      conf = top_prob.item()

    cv2.putText(frame, f"{label} {conf:.2f}", (10,30), cv2.FONT_HERSHEY_SIMPLEX, 1.0, (0,255,0), 2)
    cv2.imshow("Emotion Detector (q to quit)", frame)

    if cv2.waitKey(1) & 0xFF == ord("q"):
      break

  webcam.release()
  cv2.destroyAllWindows()

train()